stages:
  split:
    cmd: python src/data/split_dataset.py
    deps:
    - data/raw/raw.csv
    - src/data/split_dataset.py
    outs:
    - data/processed/X_test.csv
    - data/processed/X_train.csv
    - data/processed/y_test.csv
    - data/processed/y_train.csv
  normalize:
    cmd: python src/data/normalize_dataset.py
    deps:
    - data/processed/X_test.csv
    - data/processed/X_train.csv
    - src/data/normalize_dataset.py
    outs:
    - data/processed/X_test_scaled.csv
    - data/processed/X_train_scaled.csv
